task4/HomeTask4/HomeTask4.Web/Pages/Categories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private CategoryController _categoryController;
        [BindProperty]
        public Category Created {get;set;}

        public CreateModel(CategoryController categoryController)
        {
            Created = new Category();
            _categoryController = categoryController;
        }
        public void OnGet(int? parentId)
        {
            Created.ParentId = parentId;
        }
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (ModelState.IsValid){
                try
                {
                    await _categoryController.CreateCategoryAsync(Created);
                    return RedirectToPage("Index", new { Id = Created.ParentId });
                }catch(Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Categories/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Categories
{
    public class EditModel : PageModel
    {
        private CategoryController _categoryController;
        [BindProperty]
        public Category toEdit { get; set; } 

        public EditModel(CategoryController categoryController)
        {
            _categoryController = categoryController;
        }
        public async Task OnGetAsync(int? Id)
        {
            if (Id != null)
            {
                toEdit = await _categoryController.GetCategoryByIdAsync((int) Id);
            }
        }
        public async Task<IActionResult> OnPostEditAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _categoryController.UpdateCategoryAsync(toEdit);
                    return RedirectToPage("Index", new { Id = toEdit.ParentId });
                }
                catch (Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Ingredients/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Ingredients
{
    public class CreateModel : PageModel
    {
        private IngredientController _ingredientController;
        [BindProperty]
        public Ingredient Created {get;set;}

        public CreateModel(IngredientController ingredientController)
        {
            Created = new Ingredient();
            _ingredientController = ingredientController;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (ModelState.IsValid){
                try
                {
                    await _ingredientController.CreateIngredientAsync(Created);
                    return RedirectToPage("Index");
                }catch(Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Ingredients/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Ingredients
{
    public class EditModel : PageModel
    {
        private IngredientController _ingredientController;
        [BindProperty]
        public Ingredient toEdit { get; set; } 

        public EditModel(IngredientController ingredientController)
        {
            _ingredientController = ingredientController;
        }
        public async Task OnGetAsync(int? Id)
        {
            if (Id != null)
            {
                toEdit = await _ingredientController.GetIngredientByIdAsync((int) Id);
            }
        }
        public async Task<IActionResult> OnPostEditAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _ingredientController.UpdateIngredientAsync(toEdit);
                    return RedirectToPage("Index");
                }
                catch (Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Measures/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Measures
{
    public class CreateModel : PageModel
    {
        private MeasureController _measureController;
        [BindProperty]
        public Measure Created {get;set;}

        public CreateModel(MeasureController measureController)
        {
            Created = new Measure();
            _measureController = measureController;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (ModelState.IsValid){
                try
                {
                    await _measureController.CreateMeasureAsync(Created);
                    return RedirectToPage("Index");
                }catch(Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Measures/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Measures
{
    public class EditModel : PageModel
    {
        private MeasureController _measureController;
        [BindProperty]
        public Measure toEdit { get; set; } 

        public EditModel(MeasureController measureController)
        {
            _measureController = measureController;
        }
        public async Task OnGetAsync(int? Id)
        {
            if (Id != null)
            {
                toEdit = await _measureController.GetMeasureByIdAsync((int) Id);
            }
        }
        public async Task<IActionResult> OnPostEditAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _measureController.UpdateMeasureAsync(toEdit);
                    return RedirectToPage("Index");
                }
                catch (Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Recipes
{
    public class CreateModel : PageModel
    {
        private RecipeController _recipeController;
        [BindProperty]
        public Recipe Created {get;set;}

        public CreateModel(RecipeController recipeController)
        {
            Created = new Recipe();
            _recipeController = recipeController;
        }
        public void OnGet(int? categoryId)
        {
            Created.CategoryId = categoryId;
        }
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (ModelState.IsValid){
                try
                {
                    await _recipeController.CreateRecipeAsync(Created);
                    return RedirectToPage("/Recipes/Index");
                }catch(Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HomeTask4.Web.Pages.Recipes
{
    public class EditModel : PageModel
    {
        private RecipeController _recipeController;
        private MeasureController _measureController;
        private CategoryController _categoryController;
        private IngredientDetailController _ingredientDetailController;
        private RecipeStepController _recipeStepController;
        public SelectList Measures { get; set; }
        public SelectList Categories { get; set; }
        [BindProperty]
        public Recipe RecipeToEdit { get; set; } 

        public EditModel(RecipeController recipeController, 
            MeasureController measureController, 
            CategoryController categoryController , 
            IngredientDetailController ingredientDetailController,
            RecipeStepController recipeStepController)
        {
            _recipeController = recipeController;
            _measureController = measureController;
            _categoryController = categoryController;
            _ingredientDetailController = ingredientDetailController;
            _recipeStepController = recipeStepController;
        }
        public async Task OnGetAsync(int? Id)
        {
            if (Id != null)
            {
                RecipeToEdit = await _recipeController.GetRecipeByIdAsync((int) Id);
                RecipeToEdit.Steps = RecipeToEdit.Steps.OrderBy(x => x.StepNumber).ToList();
                Measures = new SelectList( await _measureController.GetAllMeasuresAsync(),"Id", "Name");
                Categories = new SelectList(await _categoryController.GetAllCategoriesAsync(), "Id", "Name");
            }
        }
        public async Task<IActionResult> OnPostEditAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _recipeController.UpdateRecipeAsync(RecipeToEdit);
                    return RedirectToPage("Index");
                }
                catch (Exception)
                {
                    return RedirectToPage("/Error");
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAddIngredientAsync(string newIngredient, double newAmount, int measureId)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    await _recipeController.AddIngredientToRecipeAsync(RecipeToEdit, newIngredient, newAmount, measureId);
                }
                catch (Exception)
                {
                    return RedirectToPage("/Error");
                }
            } else
            {
                return RedirectToPage("/Error");

            }
            
            return RedirectToPage("/Recipes/Edit", new {Id = RecipeToEdit.Id });
        }

        public async Task<IActionResult> OnPostDeleteIngredientAsync(int recipeId, int ingredientId)
        {
            try
            {
                await _ingredientDetailController.DeleteIngredientDetailByIdsAsync(recipeId, ingredientId);
            }
            catch (Exception)
            {
                return RedirectToPage("/Error");
            }
            return RedirectToPage("Edit", new { Id = RecipeToEdit.Id });
        }
        public async Task<IActionResult> OnPostDeleteStepAsync(int stepId)
        {
            try
            {
                await _recipeStepController.DeleteStepByIdAsync(stepId);
            }
            catch (Exception)
            {
                return RedirectToPage("/Error");
            }
            return RedirectToPage("Edit", new { Id = RecipeToEdit.Id });
        }

        public async Task<IActionResult> OnPostAddStepAsync(string description)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _recipeStepController.AddStepToRecipeAsync(RecipeToEdit, description);
                }
                catch (Exception)
                {
                    return RedirectToPage("/Error");
                }
            } 
            return RedirectToPage("/Recipes/Edit", new { Id = RecipeToEdit.Id });
        }

    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTask4.Core.Controllers;
using HomeTask4.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeTask4.Web.Pages.Recipes
{
    public class IndexModel : PageModel
    {
        private RecipeController _recipeController;
        public List<Recipe> Recipes { get; set; }
        public IndexModel(RecipeController recipeController)
        {
            _recipeController = recipeController;
        }
        public async Task OnGetAsync()
        {
            Recipes = await _recipeController.GetAllRecipesAsync();
        }
        public async Task<IActionResult> OnPostDeleteAsync(int deleteId)
        {
            try
            {
                await _recipeController.DeleteRecipeByIdAsync(deleteId);
            }
            catch (Exception)
            {
                return RedirectToPage("/Error");
            }
            return RedirectToPage("Index");
        }
    }
}

task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Create.cshtml
@page "{categoryId:int?}"
@model HomeTask4.Web.Pages.Recipes.CreateModel
@{
    ViewData["Title"] = "Recipe creation page";
}
<div class="container">
    <form method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input asp-for="Created.CategoryId" hidden />
            <div>
                <label asp-for="Created.Name"></label><br />
                <input class="form-control" asp-for="Created.Name" type="text" placeholder="Recipe Name" />
                <span asp-validation-for="Created.Name"></span>
            </div>
            <div>
                <label asp-for="Created.Description"></label><br />
                <input class="form-control" asp-for="Created.Description" type="text" placeholder="Description" />
            </div>
            <button asp-page-handler="Create" type="submit" class="btn btn-success">Create</button>
        </div>
    </form>
</div>
@section scripts{
    @{await Html.PartialAsync("_ValidationScriptsPartial"); }
}

task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Edit.cshtml
@page "{Id:int?}"
@model HomeTask4.Web.Pages.Recipes.EditModel
@{
    ViewData["Title"] = "Edit recipe page";
}
<div class="container">
    <h5 class="h3">Edit recipe page</h5>
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <form method="post">
        <div class="row">
            <div class="card" style="margin:5px">
                <div class="card-body">
                    <div>
                        <input asp-for="RecipeToEdit.Id" hidden />
                    </div>
                    <button type="submit" asp-page-handler="Edit" class="btn btn-success" style="display:block">Save changes</button>
                    <div>
                        <label asp-for="RecipeToEdit.Name"></label><br />
                        <input asp-for="RecipeToEdit.Name" class="form-control" type="text" placeholder="Recipe Name" />
                        <span asp-validation-for="RecipeToEdit.Name"></span>
                    </div>
                    <div>
                        <label asp-for="RecipeToEdit.Category.Name">Category:</label><br />
                        <select asp-for="RecipeToEdit.CategoryId" asp-items="@Model.Categories" class="custom-select"></select>
                    </div>
                    <div>
                        <label asp-for="RecipeToEdit.Description"></label><br />
                        <input asp-for="RecipeToEdit.Description" class="form-control" type="text" placeholder="Description">
                    </div>
                    <h5>Ingredients:</h5>
                    <ul class="list-group list-group-flush" id="card-ingredients">
                        @for (int i = 0; i < Model.RecipeToEdit.Ingredients.Count; i++)
                        {
                            <li class="list-group-item " style="display:flex">
                                <input value="@Model.RecipeToEdit.Ingredients[i].Ingredient.Name" class="form-control" type="text" placeholder="Ingredient Name" disabled />
                                <input value="@Model.RecipeToEdit.Ingredients[i].Amount " class="form-control" type="text" placeholder="Amount" disabled />
                                <input value="@Model.RecipeToEdit.Ingredients[i].Measure.Name" class="form-control" type="text" placeholder="Amount" disabled />
                                <button asp-route-recipeId="@Model.RecipeToEdit.Ingredients[i].RecipeId" asp-route-ingredientId="@Model.RecipeToEdit.Ingredients[i].IngredientId" asp-page-handler="DeleteIngredient" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete @Model.RecipeToEdit.Ingredients[i].Ingredient.Name ingredient?')">Delete</button>
                            </li>
                        }
                        <p>New Ingredient</p>
                        <li class="list-group-item">
                            <input name="newIngredient" class="form-control" type="text" placeholder="Ingredient Name" />
                            <input name="newAmount" class="form-control" type="text" placeholder="Amount" />
                            <select name="measureId" asp-items="Model.Measures" class="custom-select"></select>
                            <button asp-page-handler="AddIngredient" asp-route-Id="@Model.RecipeToEdit.Id" class="btn btn-success">Add ingredient</button>
                        </li>
                    </ul>
                    <h5>Steps:</h5>
                    <ul class="list-group list-group-flush" id="card-ingredients">
                        @for (int i = 0; i < Model.RecipeToEdit.Steps.Count; i++)
                        {
                            <li class="list-group-item" style="display:flex">
                                <input value="@Model.RecipeToEdit.Steps[i].StepNumber" class="form-control" type="text" disabled />
                                <input value="@Model.RecipeToEdit.Steps[i].Description" class="form-control" type="text" disabled />
                                <button asp-route-stepId="@Model.RecipeToEdit.Steps[i].Id" asp-page-handler="DeleteStep" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete @Model.RecipeToEdit.Steps[i].StepNumber step?')">Delete</button>
                            </li>
                        }
                        New step:
                        <li class="list-group-item">
                            <input name="description" class="form-control" type="text" placeholder="Step Description" />
                            <button asp-page-handler="AddStep" asp-route-Id="@Model.RecipeToEdit.Id" class="btn btn-success">Add step</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </form>
</div>
@section scripts{
    @{await Html.PartialAsync("_ValidationScriptsPartial"); }
}

task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Index.cshtml
@page 
@model HomeTask4.Web.Pages.Recipes.IndexModel
@{
    ViewData["Title"] = "All recipes";
}
<div class="container">
    <h3 class="h3">All Recipes</h3>
    <form method="post">
        <div class="row">
            @foreach (var recipe in Model.Recipes)
            {
                recipe.Steps = recipe.Steps.OrderBy(x => x.StepNumber).ToList();
                <div class="card" style="width:32%; margin:5px">
                    <div class="card-body">
                        <h3 class="card-title">@recipe.Name</h3>
                        <h4 class="card-text">Category: @recipe.Category.Name</h4>
                        <h5>Ingredients:</h5>
                        <ul class="list-group list-group-flush" id="card-ingredients">
                            @foreach (var ingredient in recipe.Ingredients)
                            {
                                <li class="list-group-item">@ingredient.Ingredient.Name @ingredient.Amount @ingredient.Measure.Name</li>
                            }
                        </ul>
                        <p class="card-text">Description: @recipe.Description</p>
                        <div id="card-steps">
                            @foreach (var step in recipe.Steps)
                            {
                                <p class="card-text">@step.StepNumber @step.Description</p>
                            }
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="btn-toolbar text-center" style="display:inherit">
                            <a asp-page="Edit" asp-route-Id="@recipe.Id" class="btn btn-sm btn-primary" style="border-radius: 3px 0 0 3px">Edit</a>
                            <button type="submit" asp-page-handler="Delete" asp-route-deleteId="@recipe.Id" class="btn btn-sm btn-danger" style="border-radius: 0 3px 3px 0" onclick="return confirm('Are you sure you want to delete @recipe.Name recipe?')">Delete</button>
                        </div>
                    </div>
                </div>
             }
        </div>
    </form>
</div>